version: "2.1"

services:
  nodejs-docker:
    container_name: nodejs-docker-prod
    image: nodejs-docker-prod
    restart: always
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb-prod
    image: mongo
    environment:      
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"
